# Site settings file!
# cd /Users/aviscont/Documents/GitHubGeneral/RBORsite 
# (Or wherever your RBORsite file is on your computer)
# bundle exec jekyll serve --watch

# Site settings
title: Bean and Nothingness
description: 'Bean and Nothingness' 
#keywords: "puzzle, game"
#Uncomment line above and add more SEO keywords if desired

markdown: kramdown
baseurl: ""
permalink: pretty
permalink: /:year/:month/:day/:title/

gems:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3
paginate_path: "/page:num"

exclude: ["Gemfile", "Gemfile.lock"]